/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wfjckuqfppnwyfvgpzzo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmamNrdXFmcHBud3lmdmdwenpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwOTkzNjksImV4cCI6MjA4MDY3NTM2OX0.6gHPzoFoZuM-J7-Y0FvbSzXb84VphheDJmCsnlbcpWQ"